# Big Data in Finance: Part II (Lecture 1) <BR><BR> Lecture Notes 4: Merge CRSP and Compustat 
    
**Instructor** <BR>
Lira Mota, lmota20@gsb.columbia.edu
    
**TA's:** <BR>
Pu He, phe19@gsb.columbia.edu <BR> Daheng Yang, dyang22@gsb.columbia.edu

**Objective:** <BR>
    
Create a final data set called "stock_annual" that has both crsp (permno/permco) and compustat (gvkey) identifiers.

## Query CRSP/Compustat merged table (annual or quarterly).

1. Output table is CRSP-centric with permno-datadate being the primary key.
2. Fiscal period end date must be within link date range.
3. WRDS SAS code can be found [here](https://wrds-web.wharton.upenn.edu/wrds/support/Data/_003Sample%20Programs/CRSP/index.cfm?).

## Set Up

In [1]:
#%% Packages 
import wrds
import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import time
from time import strptime, strftime

# Setups
pd.set_option("display.max_rows", 100) # max number or rows to be displayed 
%matplotlib inline 
plt.rcParams['figure.figsize'] = [10, 6]

In [2]:
db = wrds.Connection(wrds_username='lmota')  # make sure to configure wrds connector before hand.

Loading library list...
Done

## Many Linking Tables

In [3]:
crsp_tables = db.list_tables(library="crspq") # compd: Compustat daily update
pd.DataFrame({'tables':crsp_tables}) # Transform libs to a Pandas data frame to have a better display.

                       tables
0                        acti
1                        asia
2                        asib
3                        asic
4                        asio
5                        asix
6                      bmdebt
7                    bmheader
8                    bmpaymts
9                    bmquotes
10                    bmyield
11                   bndprt06
12                   bndprt12
13                   bxcalind
14                   bxdlyind
15                   bxmthind
16                   bxquotes
17                    bxyield
18                        cap
19                 ccm_lookup
20                 ccm_qvards
21           ccmxpf_linktable
22             ccmxpf_lnkhist
23              ccmxpf_lnkrng
24             ccmxpf_lnkused
25                   comphead
26                   comphist
27                 compmaster
28               contact_info
29               crsp_cik_map
30            crsp_daily_data
31                crsp_header
32          crsp_monthly_data
33                 crsp_names
34            crsp_portno_map
35     crsp_ziman_daily_index
36   crsp_ziman_monthly_index
37                     cs20yr
38                      cs5yr
39                      cs90d
40                   cst_hist
41                  daily_nav
42              daily_nav_ret
43              daily_returns
44                  dividends
45                     dport1
46                     dport2
47                     dport3
48                     dport4
49                     dport5
..                        ...
227                saz_indhdr
228                  saz_mdel
229                  saz_mind
230                   saz_mth
231                   saz_nam
232                   saz_ndi
233                   saz_shr
234                   sechead
235                   sechist
236                    sector
237                  sfz_dind
238                sfz_indhdr
239                   sfz_mbr
240                  sfz_mind
241                 sfz_portd
242                 sfz_portm
243                    sfz_rb
244              stock_qvards
245                stocknames
246              stocknames62
247         sub_property_type
248                   tfz_dly
249                tfz_dly_cd
250               tfz_dly_cpi
251                tfz_dly_ft
252               tfz_dly_rf2
253               tfz_dly_ts2
254                   tfz_idx
255                   tfz_iss
256                  tfz_mast
257                   tfz_mth
258                tfz_mth_bp
259                tfz_mth_cd
260               tfz_mth_cpi
261                tfz_mth_fb
262                tfz_mth_ft
263                tfz_mth_rf
264               tfz_mth_rf2
265                tfz_mth_ts
266               tfz_mth_ts2
267                   tfz_pay
268                        vg
269                  yldask06
270                  yldask12
271                  yldave06
272                  yldave12
273                  yldbid06
274                  yldbid12
275           ziman_reit_info
276               zr_hdrnames

[277 rows x 1 columns]

**CCMXPF_LNKHIST - Link History**


* CCMXPF_LNKHIST contains the historical and current links between GVKEY and LPERMNO/LPERMCO (previously known as NPERMN O/NPERMCO in old version CCM). 


* In addition, it includes the beginning and ending dates for links, the link types, and the primary issue marker, and liid codes (Compustat's secondary ID variable, IID).

[Source](https://wrds-www.wharton.upenn.edu/pages/support/research-wrds/research-guides/ccm-sas-datasets/)

## Many Linking Types

In [4]:
db.describe_table(library="crspq", table="ccmxpf_lnkhist")

Approximately 101711 rows in crspq.ccmxpf_lnkhist.

        name  nullable              type
0      gvkey      True        VARCHAR(6)
1   linkprim      True        VARCHAR(1)
2       liid      True        VARCHAR(3)
3   linktype      True        VARCHAR(2)
4    lpermno      True  DOUBLE PRECISION
5    lpermco      True  DOUBLE PRECISION
6     linkdt      True              DATE
7  linkenddt      True              DATE

LINKPRIM: Primary issue marker for the link.

## Download Data

In [5]:
sql = '''SELECT gvkey, lpermno as permno, lpermco as permco, linktype, linkdt, linkenddt
         FROM crspq.ccmxpf_lnkhist
         WHERE linktype IN ('LC', 'LU', 'LS') 
      ''' 

link_table = db.raw_sql(sql, date_cols=['linkdt', 'linkenddt'])

In [6]:
compa = pd.read_pickle('C:/Users/lmota20/Dropbox/Columbia/BigData/class2019/Lecture_I/outputs/compa_annual.pkl')

## Understading Linking Table

In [7]:
link_table[link_table.permco==54311]

        gvkey   permno   permco linktype     linkdt  linkenddt
14499  017010  13757.0  54311.0       LC 2013-01-14 2016-04-17
14500  017010  13758.0  54311.0       LC 2013-01-14 2016-04-15
14501  017010  14811.0  54311.0       LC 2014-07-24 2016-04-17
14502  017010  15998.0  54311.0       LC 2016-04-18 2017-12-31
14503  017010  15998.0  54311.0       LC 2018-01-01        NaT
14504  017010  15999.0  54311.0       LC 2016-04-16        NaT
14505  017010  16000.0  54311.0       LC 2016-04-18 2017-12-31
14506  017010  16000.0  54311.0       LC 2018-01-01        NaT
18949  027186  15996.0  54311.0       LC 2016-04-18 2017-12-31
18950  027186  15996.0  54311.0       LC 2018-01-01        NaT
18951  027186  15997.0  54311.0       LC 2016-04-18 2017-12-31
18952  027186  15997.0  54311.0       LC 2018-01-01        NaT
18953  027187  13757.0  54311.0       LS 2016-04-18 2017-12-31
18954  027187  13757.0  54311.0       LS 2018-01-01        NaT
18955  027187  14811.0  54311.0       LS 2016-04-18 2017-12-31
18956  027187  14811.0  54311.0       LS 2018-01-01        NaT

## Merge and Link

* Link type code. Each link is given a code describing the connection between the CRSP and Compustat data. 

* Values are:

    * LC – Link research complete. Standard connection between databases.
    * LU – Unresearched link to issue by CUSIP
    * LS – Link valid for this security only. Other CRSP PERMNOs with the same PERMCO will link to other GVKEYs.
    * LX – Link to a security that trades on another exchange system not included in CRSP data.
    * LD – Duplicate Link to a security. Another GVKEY/IID is a better link to that CRSP record.
    * LN – Primary link exists but Compustat does not have prices.
    * NR – No link available, confirmed by research
    * NU – No link available, not yet confirmed

In [8]:
link_table.linktype.value_counts()

LU    16277
LC    13355
LS     3030
Name: linktype, dtype: int64

In [9]:
df = pd.merge(compa, link_table, on=['gvkey'], how='inner')

In [10]:
df = df[(df.datadate >= df.linkdt) | (df.linkdt.isnull())]
df = df[(df.datadate <= df.linkenddt) | (df.linkenddt.isnull())]

In [11]:
df['permno'] = df['permno'].astype(int)
df['permco'] = df['permco'].astype(int)
df['datadate'] = pd.to_datetime(df['datadate'])

In [16]:
df.shape

(261633, 53)

In [17]:
compa.shape

(407279, 48)

In [29]:
df.duplicated(subset=['permno', 'datadate']).sum()

0

## Special Cases

### Many PERMCOs for One GVKEY

In [19]:
df.groupby('gvkey').permco.nunique().max()

4

In [20]:
df.loc[df.gvkey==df.groupby('gvkey').permco.nunique().idxmax(), ['datadate', 'permno', 'permco','gvkey', 'conm', 'at']]

         datadate  permno  permco   gvkey   conm         at
291345 1995-12-31   81875    4388  032280  STARZ   2517.636
291352 1996-12-31   81875    4388  032280  STARZ   3058.952
291359 1997-12-31   81875    4388  032280  STARZ   5038.561
291366 1998-12-31   81875    4388  032280  STARZ  20348.000
291374 1999-12-31   86746   20103  032280  STARZ  58684.000
291381 2000-12-31   86746   20103  032280  STARZ  54268.000
291389 2001-12-31   89130   41998  032280  STARZ  48539.000
291396 2002-12-31   89130   41998  032280  STARZ  39685.000
291403 2003-12-31   89130   41998  032280  STARZ  54013.000
291410 2004-12-31   89130   41998  032280  STARZ  50181.000
291417 2005-12-31   89130   41998  032280  STARZ  41952.000
291425 2006-12-31   91275   41998  032280  STARZ  27849.000
291426 2006-12-31   91276   41998  032280  STARZ  27849.000
291432 2007-12-31   91275   41998  032280  STARZ  26487.000
291433 2007-12-31   91276   41998  032280  STARZ  26487.000
291439 2008-12-31   91275   41998  032280  STARZ   8361.000
291440 2008-12-31   91276   41998  032280  STARZ   8361.000
291446 2009-12-31   91275   41998  032280  STARZ   9373.000
291447 2009-12-31   91276   41998  032280  STARZ   9373.000
291453 2010-12-31   91275   41998  032280  STARZ   8189.000
291454 2010-12-31   91276   41998  032280  STARZ   8189.000
291455 2011-12-31   13008   53884  032280  STARZ   7723.000
291456 2011-12-31   13009   53884  032280  STARZ   7723.000
291462 2012-12-31   13008   53884  032280  STARZ   2176.050
291463 2012-12-31   13009   53884  032280  STARZ   2176.050
291469 2013-12-31   13008   53884  032280  STARZ   1449.998
291470 2013-12-31   13009   53884  032280  STARZ   1449.998
291476 2014-12-31   13008   53884  032280  STARZ   1573.200
291477 2014-12-31   13009   53884  032280  STARZ   1573.200
291483 2015-12-31   13008   53884  032280  STARZ   1564.200
291484 2015-12-31   13009   53884  032280  STARZ   1564.200

### Many GVKEYs for one PERMCO

In [21]:
df[df['at'].notnull()].groupby('permco').gvkey.nunique().max()

5

In [22]:
pp = df[df['at'].notnull()].groupby('permco').gvkey.nunique().idxmax()

In [23]:
df.loc[df.permco==pp, ['datadate', 'permno', 'permco','gvkey', 'conm', 'at']].sort_values(['datadate'])

,datadate,permno,permco,gvkey,conm,at
336696,1994-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,NaN
336697,1995-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,NaN
157632,1996-12-31,10324,8243,012233,GENZYME CORP,1229.519
336698,1996-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,42.593
157633,1997-12-31,10324,8243,012233,GENZYME CORP,1203.056
336699,1997-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,56.818
335801,1998-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,35.952
336700,1998-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,18.954
157634,1998-12-31,10324,8243,012233,GENZYME CORP,1646.307
336701,1999-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,19.648
157635,1999-12-31,10324,8243,012233,GENZYME CORP,1399.583
335802,1999-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,9.692
339166,1999-12-31,86970,8243,121742,GENZYME SURGICAL PRODUCTS,370.924
335803,2000-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,30.752
352975,2000-12-31,88838,8243,143176,GENZYME BIOSURGERY,811.600
157636,2000-12-31,10324,8243,012233,GENZYME CORP,2499.053
157637,2001-12-31,10324,8243,012233,GENZYME CORP,3225.254
352976,2001-12-31,88838,8243,143176,GENZYME BIOSURGERY,704.671
335804,2001-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,42.419
352977,2002-12-31,88838,8243,143176,GENZYME BIOSURGERY,560.792
157638,2002-12-31,10324,8243,012233,GENZYME CORP,3555.801
335805,2002-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,13.981
157639,2003-12-31,10324,8243,012233,GENZYME CORP,5004.528
157640,2004-12-31,10324,8243,012233,GENZYME CORP,6069.421
157641,2005-12-31,10324,8243,012233,GENZYME CORP,6878.865
157642,2006-12-31,10324,8243,012233,GENZYME CORP,7191.188
157643,2007-12-31,10324,8243,012233,GENZYME CORP,8301.741
157644,2008-12-31,10324,8243,012233,GENZYME CORP,8671.276
157645,2009-12-31,10324,8243,012233,GENZYME CORP,10060.724
157646,2010-12-31,10324,8243,012233,GENZYME CORP,10913.854

### Many GVKEYs for one PERMCO for the Same Date

In [24]:
df[df['at'].notnull()].groupby(['permco','datadate']).gvkey.nunique().max()

4

In [26]:
pp = df[df['at'].notnull()].groupby(['permco','datadate']).gvkey.nunique().idxmax()
pp

(8243, Timestamp('1999-12-31 00:00:00'))

In [27]:
df.loc[df.permco==8243, ['datadate', 'permno', 'permco','gvkey', 'conm', 'at']].sort_values(['datadate'])

,datadate,permno,permco,gvkey,conm,at
336696,1994-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,NaN
336697,1995-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,NaN
157632,1996-12-31,10324,8243,012233,GENZYME CORP,1229.519
336698,1996-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,42.593
157633,1997-12-31,10324,8243,012233,GENZYME CORP,1203.056
336699,1997-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,56.818
335801,1998-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,35.952
336700,1998-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,18.954
157634,1998-12-31,10324,8243,012233,GENZYME CORP,1646.307
336701,1999-12-31,81154,8243,118653,GENZYME TISSUE REPAIR,19.648
157635,1999-12-31,10324,8243,012233,GENZYME CORP,1399.583
335802,1999-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,9.692
339166,1999-12-31,86970,8243,121742,GENZYME SURGICAL PRODUCTS,370.924
335803,2000-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,30.752
352975,2000-12-31,88838,8243,143176,GENZYME BIOSURGERY,811.600
157636,2000-12-31,10324,8243,012233,GENZYME CORP,2499.053
157637,2001-12-31,10324,8243,012233,GENZYME CORP,3225.254
352976,2001-12-31,88838,8243,143176,GENZYME BIOSURGERY,704.671
335804,2001-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,42.419
352977,2002-12-31,88838,8243,143176,GENZYME BIOSURGERY,560.792
157638,2002-12-31,10324,8243,012233,GENZYME CORP,3555.801
335805,2002-12-31,86426,8243,117298,GENZYME MOLECULAR ONCOLOGY,13.981
157639,2003-12-31,10324,8243,012233,GENZYME CORP,5004.528
157640,2004-12-31,10324,8243,012233,GENZYME CORP,6069.421
157641,2005-12-31,10324,8243,012233,GENZYME CORP,6878.865
157642,2006-12-31,10324,8243,012233,GENZYME CORP,7191.188
157643,2007-12-31,10324,8243,012233,GENZYME CORP,8301.741
157644,2008-12-31,10324,8243,012233,GENZYME CORP,8671.276
157645,2009-12-31,10324,8243,012233,GENZYME CORP,10060.724
157646,2010-12-31,10324,8243,012233,GENZYME CORP,10913.854

In [28]:
df.loc[df.permco==54311, ['datadate', 'permno', 'permco','gvkey', 'conm', 'at']].sort_values(['datadate'])

,datadate,permno,permco,gvkey,conm,at
209884,2013-12-31,13757,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,34542.0
209885,2013-12-31,13758,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,34542.0
209892,2014-12-31,13757,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,31207.0
209893,2014-12-31,13758,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,31207.0
209894,2014-12-31,14811,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,31207.0
209900,2015-12-31,13757,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,29798.0
209901,2015-12-31,13758,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,29798.0
209902,2015-12-31,14811,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,29798.0
259702,2016-12-31,14811,54311,027187,LIBERTY MEDIA FORMULA ONE,2995.0
259700,2016-12-31,13757,54311,027187,LIBERTY MEDIA FORMULA ONE,2995.0
259686,2016-12-31,15997,54311,027186,LIBERTY MEDIA BRAVES GROUP,1548.0
259684,2016-12-31,15996,54311,027186,LIBERTY MEDIA BRAVES GROUP,1548.0
209914,2016-12-31,16000,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,27051.0
209913,2016-12-31,15999,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,27051.0
209911,2016-12-31,15998,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,27051.0
209922,2017-12-31,16000,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,28530.0
209919,2017-12-31,15998,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,28530.0
259704,2017-12-31,13757,54311,027187,LIBERTY MEDIA FORMULA ONE,11802.0
259688,2017-12-31,15996,54311,027186,LIBERTY MEDIA BRAVES GROUP,1866.0
259690,2017-12-31,15997,54311,027186,LIBERTY MEDIA BRAVES GROUP,1866.0
209921,2017-12-31,15999,54311,017010,LIBERTY MEDIA SIRIUSXM GROUP,28530.0
259706,2017-12-31,14811,54311,027187,LIBERTY MEDIA FORMULA ONE,11802.0